library(feather)
library(leafem)
library(leaflet)
library(raster)
library(rgdal)
library(shiny)
library(shinyWidgets)
library(sf)
library(tidyverse)

source('https://raw.githubusercontent.com/mosscoder/mpg_herbaceous_biomass/main/gloabl.R')
source('https://raw.githubusercontent.com/mosscoder/mpg_herbaceous_biomass/main/ui.R')
source('https://raw.githubusercontent.com/mosscoder/mpg_herbaceous_biomass/main/server.R')

shinyApp(ui = ui, server = server)